reddit/config/routes.rb
Rails.application.routes.draw do
 
  resources :users, only: [:new, :create, :show, :index] 
  resource :session, only: [:create, :new, :destroy]
  resources :subs, except: [:destroy]
   resources :posts
end

reddit/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

reddit/app/models/post.rb
class Post < ApplicationRecord
    validates :title, :author_id, presence: true

    belongs_to :author,
     foreign_key: :author_id,
     class_name: :User

     has_many :postsubs,
     foreign_key: :post_id,
     class_name: :Postsub
     
     has_many :subs,
     through: :postsubs,
     source: :subs
end

reddit/app/models/postsub.rb
class Postsub < ApplicationRecord

    belongs_to :posts,
    class_name: :Post,
    foreign_key: :post_id

    belongs_to :subs,
    class_name: :Sub,
    foreign_key: :sub_id
end

reddit/app/models/sub.rb
class Sub < ApplicationRecord
    validates :title, :description, :mod_id, presence: true

    has_many :postsubs,
    class_name: :Postsubs,
    foreign_key: :sub_id

    has_many :posts,
    through: :postsubs,
    source: :posts

    belongs_to :mod,
    foreign_key: :mod_id,
    class_name: :User

end

reddit/app/models/user.rb
class User < ApplicationRecord
    validates :username , uniqueness: true, presence: true
    validates :session_token, uniqueness: true, presence: true
    validates :password_digest, presence:true
    validates :password, length: {minimum: 6, allow_nil: true}

    has_many :posts,
    foreign_key: :author_id,
    class_name: :Post

    has_many :subs_active_on,
    through: :posts,
    source: :subs

    has_many :mod_subs,
    foreign_key: :mod_id,
    class_name: :Sub


    attr_reader :password

    after_initialize :ensure_session_token

    def ensure_session_token
        self.session_token ||= SecureRandom.base64(16)
    end

    def self.find_by_credentials(username, password)
        user = User.find_by(username: username)

        return user if user && user.is_password?(password)
        
    end

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end

    def reset_session_token!
        self.session_token = SecureRandom.base64(16)
        self.save!
        self.session_token
    end

end

reddit/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :signed_in?, :sign_in,  :require_signed_in!, :sign_out!
 def current_user
  @current_user ||= User.find_by(session_token: session[:session_token]) 
 end

  def sign_in(user)
    @current_user = user 
  session[:session_token] = user.reset_session_token!
  end

  def signed_in? 
    !!current_user
  end

  def require_signed_in!
    redirect_to new_session_url if !signed_in?
    
 end

    def sign_out!
        @current_user.reset_session_token!
        session[:session_token] = nil  
    end
end

reddit/app/controllers/posts_controller.rb
class PostController < ApplicationController


end

reddit/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    before_action :require_signed_in!, only:[:destroy]

    def new
        render :new
    end

    def create
        @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
        if @user
            sign_in(@user)
            redirect_to users_url
        else 
            flash.now[:errors] = ["Invalid Username or Password"]
            render :new 
        end
    end

    def destroy
        sign_out!
        redirect_to new_session_url
    end

end

reddit/app/controllers/subs_controller.rb
class SubController < ApplicationController

   
    def new
        @sub = Sub.new
        render :new
    end

    def create

    end

    def edit
        # id 
        
        @sub = Sub.find(params[:id])
        if @sub && current_user.id == @sub.mod_id
            render :edit
        else
            flash[:errors] = ["sub does not exit"]
            redirect_to new_sub_url
        end
    end

    def update
        # params has the new data we want in our sub
        @sub = Sub.find(params[:id])
        #if update is not the way, create new and destroy old
        
        if @sub.update(update_params)
            redirect sub_url(params[:id])
        else
            flash.now[:errors] = @sub.errors.full_messages
            render :edit
        end
    end

    def index
    end

    def show

    end

    private
    def update_params
        params.require(:sub).permit(:title,:description)
    end

end

reddit/app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :require_signed_in!, only:[:show, :index]
    def new
        @user = User.new 
        render :new 
    end

    def create
        @user = User.new(user_params)
        if @user.save 
            sign_in(@user)
            redirect_to users_url 
        else
            flash.now[:errors] = @user.errors.full_messages 
            render :new 
        end
    end
    
    def show 
        # @user = User.find(params[:id]) 
        @user = User.find_by(id: params[:id])
        render :show
        #check if user is valid
    end

    def index 
      @users = User.all
      render :index 
   end

    def user_params
        params.require(:user).permit(:username, :password)
    end

end

reddit/app/helpers/application_helper.rb
module ApplicationHelper
end

reddit/app/helpers/sessions_helper.rb
module SessionsHelper
end

reddit/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reddit</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

   
  </head>

  <body>
    <div>
    <%if flash[:errors]%>
      <%= flash[:errors].join(",") %>
      <%end%> </div>
    <%= yield %>
  </body>
</html>

reddit/app/views/subs/edit.html.erb
<h1> Form for editing<h1>

<form action="<%= sub_url(@sub.id)%>" method="POST">
<input type='hidden' name='_method' value='PATCH' >
<input type='hidden' name='authenticity_token' value='<%=form_authenticity_token%>'>

<label> Title 
<input name='sub[title]' value='<%=sub.title%>'>
 </label>

 <label> Description 
<input name='sub[description]' value='<%=sub.description%>'>
 </label>

 <button type="submit"> Update Sub </button>
 </form>

reddit/app/views/subs/new.html.erb
<h1> New Sub</h1>

reddit/app/views/users/index.html.erb
<h2>All the Users </h2>


<% @users.each do |user|%>
    <a href="<%=user_url(user.id)%>"><%=user.username%> </a>
<% end %>

reddit/app/views/users/new.html.erb
<h2> Sign Up </h2>


<form action="<%=users_url%>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">

    <label>Username
        <input name="user[username]" value="<%=@user.username%>">
    </label>

    <label>Password
        <input name="user[password]" value="">
    </label>

    <button type="submit">Sign Up</button>
</form>

reddit/app/views/users/show.html.erb
<h1> <%=@user.username%>'s Page' <h2>